package br.com.projeto1.javai.servidor;

import java.util.HashMap;
import java.util.Map;

import br.com.projeto1.javai.bancodedados.BancoDeDados;

public class Servidor {

	private Map<String, BancoDeDados> server = new HashMap<>();
	
	public Servidor() {
		
		BancoDeDados remedio = new BancoDeDados("abatacepte", 1);
		BancoDeDados remedio2 = new BancoDeDados("acetazolamida", 2);
		BancoDeDados remedio3 = new BancoDeDados("ácido nicotínico",3 );
		BancoDeDados remedio4 = new BancoDeDados("ácido ursodesoxicólico", 4);
		BancoDeDados remedio5 = new BancoDeDados("ácido zoledrônico", 5);
		BancoDeDados remedio6 = new BancoDeDados("acitretina", 6);
		BancoDeDados remedio7 = new BancoDeDados("adalimumabe", 7);
		BancoDeDados remedio8 = new BancoDeDados("alfaglicosidase", 8);
		BancoDeDados remedio9 = new BancoDeDados("alfadornase", 9);
		BancoDeDados remedio10 = new BancoDeDados("alfaelosulfase", 10);
		BancoDeDados remedio11 = new BancoDeDados("alfaepoetina", 11);
		BancoDeDados remedio12 = new BancoDeDados("alfainterferona 2b", 12);
		BancoDeDados remedio13 = new BancoDeDados("amantadina", 13);
		BancoDeDados remedio14 = new BancoDeDados("ambrisentana",14);
		BancoDeDados remedio15 = new BancoDeDados("atorvastatina",15);
		BancoDeDados remedio16 = new BancoDeDados("azatioprina", 16);
		BancoDeDados remedio17 = new BancoDeDados("baricitinibe", 17);
		BancoDeDados remedio18 = new BancoDeDados("betainterferona", 18);
		BancoDeDados remedio19= new BancoDeDados("bezafibrato",19);
		BancoDeDados remedio20 = new BancoDeDados("biotina",20);
		BancoDeDados remedio21 = new BancoDeDados("brimonidina", 21);
		BancoDeDados remedio22 = new BancoDeDados("brinzolamida", 22);
		BancoDeDados remedio23 = new BancoDeDados("budesonida", 23);
		BancoDeDados remedio24 = new BancoDeDados("cabergolina", 24);
		BancoDeDados remedio25 = new BancoDeDados("calcipotriol", 25);
		BancoDeDados remedio26 = new BancoDeDados("calcitonina",26);
		BancoDeDados remedio27 = new BancoDeDados("calcitriol",27);
		BancoDeDados remedio28 = new BancoDeDados("certolizumabe pegol",28);
		BancoDeDados remedio29 = new BancoDeDados("ciclofosfamida",29);
		BancoDeDados remedio30= new BancoDeDados("ciclosporina",30);
		BancoDeDados remedio31 = new BancoDeDados("cinacalcete",31);
		BancoDeDados remedio32 = new BancoDeDados("ciprofibrato", 32);
		BancoDeDados remedio33 = new BancoDeDados("ciproterona",33);
		BancoDeDados remedio34 = new BancoDeDados("clobazam",34);
		BancoDeDados remedio35 = new BancoDeDados("clobetasol",35);
		BancoDeDados remedio36 = new BancoDeDados("clopidogrel",36);
		BancoDeDados remedio37 = new BancoDeDados("cloroquina",37);
		BancoDeDados remedio38 = new BancoDeDados("clozapina",38);
		BancoDeDados remedio39 = new BancoDeDados("codeína",39);
		BancoDeDados remedio40 = new BancoDeDados("complemento alimentar para paciente fenilcetonúrico (fórmula de aminoácidos isenta de fenilalanina", 40);
		BancoDeDados remedio41 = new BancoDeDados("danazol", 41);
		BancoDeDados remedio42 = new BancoDeDados("dapagliflozina", 42);
		BancoDeDados remedio43 = new BancoDeDados("deferasirox", 43);
		BancoDeDados remedio44 = new BancoDeDados("deferiprona", 44);
		BancoDeDados remedio45 = new BancoDeDados("desferroxamina", 45);
		BancoDeDados remedio46 = new BancoDeDados("desmopressina",46);
		BancoDeDados remedio47 = new BancoDeDados("dicloridrato de sapropterina",47);
		BancoDeDados remedio48 = new BancoDeDados("donepezila",48);
		BancoDeDados remedio49 = new BancoDeDados("dorzolamida",49);
		BancoDeDados remedio50 = new BancoDeDados("eltrombopague olamina", 50);
		BancoDeDados remedio51 = new BancoDeDados("enoxaparina sódica",51);
		BancoDeDados remedio52 = new BancoDeDados("entacapona",52);
		BancoDeDados remedio53 = new BancoDeDados("etanercepte",53);
		BancoDeDados remedio54 = new BancoDeDados("etossuximida",54);
		BancoDeDados remedio55 = new BancoDeDados("everolimo",55);
		BancoDeDados remedio56 = new BancoDeDados("fenofibrato",56);
		BancoDeDados remedio57 = new BancoDeDados("fenoterol",57);
		BancoDeDados remedio58 = new BancoDeDados("filgrastim",58);
		BancoDeDados remedio59 = new BancoDeDados("fingolimode",59);
		BancoDeDados remedio60 = new BancoDeDados("fludrocortisona",60);
		BancoDeDados remedio61 = new BancoDeDados("formoterol",61);
		BancoDeDados remedio62 = new BancoDeDados("formoterol + budesonida",62);
		BancoDeDados remedio63 = new BancoDeDados("fumarato de dimetila",63);
		BancoDeDados remedio64 = new BancoDeDados("gabapentina",64);
		BancoDeDados remedio65 = new BancoDeDados("galantamina",65);
		BancoDeDados remedio66 = new BancoDeDados("galsulfase",66);
		BancoDeDados remedio67 = new BancoDeDados("genfibrozila",67);
		BancoDeDados remedio68 = new BancoDeDados("glatiramer",68);
		BancoDeDados remedio69 = new BancoDeDados("golimumabe",69);
		BancoDeDados remedio70 = new BancoDeDados("gosserrelina", 70);
		BancoDeDados remedio71 = new BancoDeDados("hidroxicloroquina",71);
		BancoDeDados remedio72 = new BancoDeDados("hidroxiuréia",72);
		BancoDeDados remedio73 = new BancoDeDados("idursulfase alfa",73);
		BancoDeDados remedio74 = new BancoDeDados("iloprosta",74);
		BancoDeDados remedio75 = new BancoDeDados("imiglucerase",75);
		BancoDeDados remedio76 = new BancoDeDados("imunoglobulina humana",76);
		BancoDeDados remedio77 = new BancoDeDados("infliximabe",77);
		BancoDeDados remedio78 = new BancoDeDados("Insulina Asparte",78);
		BancoDeDados remedio79 = new BancoDeDados("insulina glulisina",79);
		BancoDeDados remedio80 = new BancoDeDados("isotretinoína",80);
		BancoDeDados remedio81 = new BancoDeDados("lamotrigina",81);
		BancoDeDados remedio82 = new BancoDeDados("lanreotida",82);
		BancoDeDados remedio83 = new BancoDeDados("laronidase",83);
		BancoDeDados remedio84 = new BancoDeDados("latanoprosta",84);
		BancoDeDados remedio85 = new BancoDeDados("leflunomida",85);
		BancoDeDados remedio86 = new BancoDeDados("leuprorrelina",86);
		BancoDeDados remedio87 = new BancoDeDados("levetiracetam",87);
		BancoDeDados remedio88 = new BancoDeDados("memantina",88);
		BancoDeDados remedio89 = new BancoDeDados("mesalazina",89);
		BancoDeDados remedio90 = new BancoDeDados("metadona",90);
		BancoDeDados remedio91 = new BancoDeDados("metilprednisolona",91);
		BancoDeDados remedio92 = new BancoDeDados("metotrexato",92);
		BancoDeDados remedio93 = new BancoDeDados("micofenolato de mofetila",93);
		BancoDeDados remedio94 = new BancoDeDados("micofenolato de sódio",94);
		BancoDeDados remedio95 = new BancoDeDados("miglustate",95);
		BancoDeDados remedio96 = new BancoDeDados("morfina",96);
		BancoDeDados remedio97 = new BancoDeDados("naproxeno",97);
		BancoDeDados remedio98 = new BancoDeDados("natalizumabe",98);
		BancoDeDados remedio99 = new BancoDeDados("nusinersena", 99);
		BancoDeDados remedio100 = new BancoDeDados("octreotida", 100);
		BancoDeDados remedio101 = new BancoDeDados("olanzapina", 101);
		BancoDeDados remedio102 = new BancoDeDados("omalizumabe", 102);
		BancoDeDados remedio103 = new BancoDeDados("pamidronato", 103);
		BancoDeDados remedio104 = new BancoDeDados("pancreatina", 104);
		BancoDeDados remedio105 = new BancoDeDados("paricalcitol", 105);
		BancoDeDados remedio106 = new BancoDeDados("penicilamina", 106);
		BancoDeDados remedio107 = new BancoDeDados("pilocarpina", 107);
		BancoDeDados remedio108 = new BancoDeDados("piridostigmina", 108);
		BancoDeDados remedio109 = new BancoDeDados("pramipexol", 109);
		BancoDeDados remedio110 = new BancoDeDados("pravastatina", 110);
		BancoDeDados remedio111 = new BancoDeDados("primidona", 111);
		BancoDeDados remedio112 = new BancoDeDados("quetiapina", 112);
		BancoDeDados remedio113 = new BancoDeDados("raloxifeno", 113);
		BancoDeDados remedio114 = new BancoDeDados("rasagilina", 114);
		BancoDeDados remedio115 = new BancoDeDados("riluzol", 115);
		BancoDeDados remedio116 = new BancoDeDados("risedronato", 116);
		BancoDeDados remedio117 = new BancoDeDados("risperidona", 117);
		BancoDeDados remedio118 = new BancoDeDados("rituximabe", 118);
		BancoDeDados remedio119 = new BancoDeDados("rivastigmina", 119);
		BancoDeDados remedio120 = new BancoDeDados("sacarato de hidróxido férrico", 120);
		BancoDeDados remedio121 = new BancoDeDados("sacubitril/valsartana", 121);
		BancoDeDados remedio122 = new BancoDeDados("secuquinumabe", 122);
		BancoDeDados remedio123 = new BancoDeDados("selegilina", 123 );
		BancoDeDados remedio124 = new BancoDeDados("sevelamer", 124);
		BancoDeDados remedio125 = new BancoDeDados("sildenafila", 125);
		BancoDeDados remedio126 = new BancoDeDados("sirolimo", 126);
		BancoDeDados remedio127 = new BancoDeDados("somatropina", 127);
		BancoDeDados remedio128 = new BancoDeDados("sulfassalazina", 128);
		BancoDeDados remedio129 = new BancoDeDados("tafamidis", 129);
		BancoDeDados remedio130 = new BancoDeDados("tacrolimo", 130);
		BancoDeDados remedio131 = new BancoDeDados("taliglucerase alfa", 131);
		BancoDeDados remedio132 = new BancoDeDados("teriflunomida", 132);
		BancoDeDados remedio133 = new BancoDeDados("timolol", 133);
		BancoDeDados remedio134 = new BancoDeDados("tobramicina", 134);
		BancoDeDados remedio135 = new BancoDeDados("tocilizumabe", 135);
		BancoDeDados remedio136 = new BancoDeDados("tofacitinibe", 136);
		BancoDeDados remedio137 = new BancoDeDados("topiramato", 137);
		BancoDeDados remedio138 = new BancoDeDados("toxina botulínica tipo a", 138);
		BancoDeDados remedio139 = new BancoDeDados("travoprosta",139);
		BancoDeDados remedio140 = new BancoDeDados("trientina", 140);
		BancoDeDados remedio141 = new BancoDeDados("triexifenidil", 141);
		BancoDeDados remedio142 = new BancoDeDados("triptorrelina", 142 );
		BancoDeDados remedio143 = new BancoDeDados("vedolizumabe", 143);
		BancoDeDados remedio144 = new BancoDeDados("vigabatrina", 144);
		BancoDeDados remedio145 = new BancoDeDados("ustequinumabe", 145);
		BancoDeDados remedio146 = new BancoDeDados("ziprasidona", 146);		
		
		server.put("abatacepte", remedio);
		server.put("acetazolamida", remedio2);
		server.put("ácido nicotínico", remedio3);
		server.put("ácido ursodesoxicólico", remedio4);
		server.put("ácido zoledrônico", remedio5);
		server.put("acitretina", remedio6);
		server.put("adalimumabe", remedio7);
		server.put("alfaglicosidase", remedio8);
		server.put("alfadornase", remedio9);
		server.put("alfaelosulfase", remedio10);
		server.put("alfaepoetina", remedio11);
		server.put("alfainterferona 2b", remedio12);
		server.put("amantadina", remedio13);
		server.put("ambrisentana",remedio14);
		server.put("atorvastatina",remedio15);
		server.put("azatioprina", remedio16);
		server.put("baricitinibe", remedio17);
		server.put("betainterferona", remedio18);
		server.put("bezafibrato",remedio19);
		server.put("biotina",remedio20);
		server.put("brimonidina", remedio21);
		server.put("brinzolamida", remedio22);
		server.put("budesonida", remedio23);
		server.put("cabergolina", remedio24);
		server.put("calcipotriol", remedio25);
		server.put("calcitonina", remedio26);
		server.put("calcitriol", remedio27);
		server.put("certolizumabe pegol", remedio28);
		server.put("ciclofosfamida", remedio29);
		server.put("ciclosporina", remedio30);
		server.put("cinacalcete", remedio31);
		server.put("ciprofibrato", remedio32);
		server.put("ciproterona", remedio33);
		server.put("clobazam", remedio34);
		server.put("clobetasol", remedio35);
		server.put("clopidogrel", remedio36);
		server.put("cloroquina", remedio37);
		server.put("clozapina",remedio38);
		server.put("codeína", remedio39);
		server.put("complemento alimentar para paciente fenilcetonúrico (fórmula de aminoácidos isenta de fenilalanina", remedio40);
		server.put("danazol", remedio41);
		server.put("dapagliflozina", remedio42);
		server.put("deferasirox", remedio43);
		server.put("deferiprona", remedio44);
		server.put("desferroxamina", remedio45);
		server.put("desmopressina", remedio46);
		server.put("dicloridrato de sapropterina", remedio47);
		server.put("donepezila", remedio48);
		server.put("dorzolamida", remedio49);
		server.put("eltrombopague olamina", remedio50);
		server.put("enoxaparina sódica", remedio51);
		server.put("entacapona", remedio52);
		server.put("etanercepte", remedio53);
		server.put("etossuximida", remedio54);
		server.put("everolimo", remedio55);
		server.put("fenofibrato", remedio56);
		server.put("fenoterol", remedio57);
		server.put("filgrastim", remedio58);
		server.put("fingolimode", remedio59);
		server.put("fludrocortisona", remedio60);
		server.put("formoterol", remedio61);
		server.put("formoterol + budesonida", remedio62);
		server.put("fumarato de dimetila", remedio63);
		server.put("gabapentina", remedio64);
		server.put("galantamina", remedio65);
		server.put("galsulfase", remedio66);
		server.put("genfibrozila", remedio67);
		server.put("glatiramer", remedio68);
		server.put("golimumabe", remedio69);
		server.put("gosserrelina", remedio70);
		server.put("hidroxicloroquina", remedio71);
		server.put("hidroxiuréia", remedio72);
		server.put("idursulfase alfa", remedio73);
		server.put("iloprosta", remedio74);
		server.put("imiglucerase", remedio75);
		server.put("imunoglobulina humana", remedio76);
		server.put("infliximabe", remedio77);
		server.put("Insulina Asparte", remedio78);
		server.put("insulina glulisina ", remedio79);
		server.put("isotretinoína", remedio80);
		server.put("lamotrigina", remedio81);
		server.put("lanreotida", remedio82);
		server.put("laronidase", remedio83);
		server.put("latanoprosta", remedio84);
		server.put("leflunomida", remedio85);
		server.put("leuprorrelina", remedio86);
		server.put("levetiracetam", remedio87);
		server.put("memantina", remedio88);
		server.put("mesalazina", remedio89);
		server.put("metadona", remedio90);
		server.put("metilprednisolona", remedio91);
		server.put("metotrexato", remedio92);
		server.put("micofenolato de mofetila", remedio93);
		server.put("micofenolato de sódio", remedio94);
		server.put("miglustate", remedio95);
		server.put("morfina", remedio96);
		server.put("naproxeno", remedio97);
		server.put("natalizumabe", remedio98);
		server.put("nusinersena", remedio99);
		server.put("octreotida", remedio100);
		server.put("olanzapina", remedio101);
		server.put("omalizumabe", remedio102);
		server.put("pamidronato", remedio103);
		server.put("pancreatina", remedio104);
		server.put("paricalcitol", remedio105);
		server.put("penicilamina", remedio106);
		server.put("pilocarpina", remedio107);
		server.put("piridostigmina", remedio108);
		server.put("pramipexol", remedio109);
		server.put("pravastatina", remedio110);
		server.put("primidona", remedio111);
		server.put("quetiapina", remedio112);
		server.put("raloxifeno", remedio113);
		server.put("rasagilina", remedio114);
		server.put("riluzol", remedio115);
		server.put("risedronato", remedio116);
		server.put("risperidona", remedio117);
		server.put("rituximabe", remedio118);
		server.put("rivastigmina", remedio119);
		server.put("sacarato de hidróxido férrico", remedio120);
		server.put("sacubitril/valsartana", remedio121);
		server.put("secuquinumabe", remedio122);
		server.put("selegilina", remedio123 );
		server.put("sevelamer", remedio124);
		server.put("sildenafila", remedio125);
		server.put("sirolimo", remedio126);
		server.put( "somatropina", remedio127);
		server.put("sulfassalazina", remedio128);
		server.put("tafamidis", remedio129);
		server.put("tacrolimo", remedio130);
		server.put("taliglucerase alfa", remedio131);
		server.put("teriflunomida", remedio132);
		server.put("timolol", remedio133);
		server.put("tobramicina", remedio134);
		server.put("tocilizumabe", remedio135);
		server.put("tofacitinibe", remedio136);
		server.put( "topiramato", remedio137);
		server.put( "toxina botulínica tipo a", remedio138);
		server.put("travoprosta", remedio139);
		server.put("trientina", remedio140);
		server.put("triexifenidil", remedio141);
		server.put("triptorrelina", remedio142 );
		server.put("vedolizumabe", remedio143);
		server.put("vigabatrina", remedio144);
		server.put("ustequinumabe", remedio145);
		server.put("ziprasidona", remedio146);
				
		
	}
	
	public BancoDeDados remedioNome(String nome) {
		
		
		return server.get(nome);
		
	}
}
